### ISSUE TITLE
Métodos getDeviceMetadata() e setDeviceMetadata() com o novo padrão de Entry para os devices

### ISSUE THREAD

**Issue by LucasHMS** [AndreJCL/JCL#53]
Existe alguma forma de recuperar o endereço IP dos Devices na hora de conectar a eles? Preciso disso para que possa alterar ou retornar o config.properties deles para o user quando ele chama algum desses métodos da API. Dê uma olhada na FacadeImpl nos métodos getDeviceMetadata() e setDeviceMetadata() para ver como estava sendo feito.

**Comment by AndreJCL** [comment]
É possível através do método getDeviceMetadata(). Mudança de nome do método que configura o arquivo ..properties para getDeviceConfig() e setDeviceConfig(). Criação do loadConfig().
