### ISSUE TITLE
[IoT] Verificação nos métodos de addContextAction

### ISSUE THREAD

**Issue by samuelqsrocha** [AndreJCL/JCL#55]
Antes de adicionar um contexto, verificar se o contexto em questão já foi registrado. Nos testes foram passados nomes de contextos que não foram registrados.

**Comment by leoscimino** [comment]
Foi adicionada a verificação nos métodos que usam contexto (registerContext, unregisterContext, addContextAction, registerMQTTContext e unregisterMQTTContext)
