### ISSUE TITLE
[IoT] Problemas no setSensorMetadata

### ISSUE THREAD

**Issue by samuelqsrocha** [AndreJCL/JCL#62]
Quando é passado "" (abre e fecha aspas) ou " " (abre, espaço e fecha aspas) como nome do sensor, o sensor ainda sim é setado sem nome. 
Quando todos os valores inteiros, exceto o valor do pino, passados são negativos trava a execução.
Quando a string que define se é input ou output é passada como "" (abre e fecha aspas), a execução trava, mas quando passa " " (abre, espaço e fecha aspas), o método retorna true.

**Comment by leoscimino** [comment]
O problema foi tratado. Agora não é mais possível passar argumentos como "" ou " ". 
Também não é mais permitido que o usuário passe argumentos negativos como, por exemplo, no tempo de intervalo de sensoriamento ou número máximo de registros a serem salvos.
