### ISSUE TITLE
discover no JCL - tirar o conceito de server explicito

### ISSUE THREAD

**Issue by joubertlima** [AndreJCL/JCL#71]
acho q podemos desenvolver um protocolo simples que cada Host ou super-peer possuirá. Cada device ao entrar no cluster tenta ser o server deste. se ja houver, ele vira Host ou super-peer apenas. se nao houver ele vira o server tb

com isto, evitamos ter maquinas exclusivas pro server e simplificamos o deploy ainda mais....

ponto fraco: o server faz túneis, portanto ele pode gerar consumo alto de CPU, dae o instalar junto com outro componente JCL pode atrapalhar. Sugiro deixar o usuário optar por instalar o server explicitamente ou deixar q o JCL o eleja dinamicamente...

**Comment by leoscimino** [comment]
Discover implementado
