### ISSUE TITLE
Bug ao tentar pegar valor de um Global Var ainda inexistente no JCL (Release 1.0)

### ISSUE THREAD

**Issue by LucasHMS** [AndreJCL/JCL#78]
Segundo a API, quando é feito um `getValue("GV_inexistente")` ou `getValueLocking("GV_inexistente")` em e a global var de nome `GV_inexistente`  não tenha sido instanciada dentro do JCL, o retorno de ambos os métodos seria `null`, porém o retorno é diferente de `null` mesmo depois de fazer um `getCorrectResult()`  depois de tentar recuperar o valor da global var. Segue um exemplo mínimo da situação:

```
Object o = jcl.getValue("gv_inexistente");
System.out.println(o==null);
```
ou 
```
Object o = jcl.getValue("gv_inexistente").getCorrectResult();
System.out.println(o==null);
```

Ambos os casos exibem `false`

OBS: acredito ter um teste unitário com um caso semelhante a isso. Irei se realmente existe um caso desse.

**Comment by LucasHMS** [comment]
Realmente existe um caso de teste que tem essa finalidade, porém está mal projetado [linhas 148 e 153](https://github.com/AndreJCL/JCL/blob/master/src/test/java/junit/JCL_FacadeImplTestLambari.java). Irei adicionar um caso de teste que cubra o problema relatado.

**Comment by AndreJCL** [comment]
Problema solucionado. O null internamente era interpretado como "no result".
