### ISSUE TITLE
[IoT] Problema quando duas aplcações usam setSensor para o mesmo sensor

### ISSUE THREAD

**Issue by LucasHMS** [AndreJCL/JCL#80]
Tenho uma aplicação configura dois sensores numa placa e depois é feito um execute em um método. Ele realiza um acting em um dos sensores configurados (no caso um servo). Segue o código que faz a configuração.

```
Device galileo = iot.<Device>getDeviceByName("gal").get(0);
devices.add(galileo);
// configurando o sensor de luminosidade no pino 0
iot.setSensorMetadata(galileo, "luminosidade", 0, numMaxRegistro, delay, Constants.IoT.INPUT, Constants.IoT.GENERIC);
// configurando o servo no pino 6
iot.setSensorMetadata(galileo, "servo", 6, numMaxRegistro, delay, Constants.IoT.OUTPUT, Constants.IoT.SERVO);
```
O problema surge quando essa mesma aplicação é executada mais de uma vez. A primeira execução ocorre como esperado. Os sensores são setados e todos os devices do cluster invocam o acting atravez do execute. Na segunda execução, somente recebe-se a mensagem de *** Set Sensor *** e não chega executar o acting.

Esse é o código que é chamdo nos executes:
```
public void actuate(Device device, Entry<String,String> actuator, Object [] args) {
	iot.acting(device, actuator, args);
}
```

**Comment by leoscimino** [comment]
Problema corrigido
