### ISSUE TITLE
[IoT] bug ao usar addAction em multiplas threads

### ISSUE THREAD

**Issue by LucasHMS** [AndreJCL/JCL#81]
Quando a aplicação inicia multiplos `addContext()` para um único context, o JCL parece não responder. Mesmo que contexto que está sendo ligado a action em questão tenha sido alcançado, a ação não é adicionada ou acionada. O seguinte código para no momento em que tento adicionar a action:
```
public void startAction(String ctxName, Entry<String,String> device, Entry<String,String> actuator, Object [] args) {
	System.out.println("action");
	boolean res = iot.addContextAction(ctxName, device, actuator, args);
	System.out.println(res);
}
```
Esse método é passado para um executeAll que roda em todos os devices do cluster, ou seja, multiplas threads tentam adicionar uma  mesma action para o contexto. A adição do contexto, por outro lado, funciona para multliplas threads, inclusive apresenta a mensagem `*** context reached ***` quando o contexto é alcançado.

**Comment by leoscimino** [comment]
Problema corrigido
