### ISSUE TITLE
[Android IoT] Bug ao usar os data types no android

### ISSUE THREAD

**Issue by LucasHMS** [AndreJCL/JCL#82]
Ao tentar usar método em um execute que recebia como parâmetro um Device, uma é exceção é lançada no Android, segue um print do erro no momento que o código tenta rodar o execute:

![screenshot_20171207-192311](https://user-images.githubusercontent.com/13833565/33746281-514af628-dba3-11e7-8aca-66425d2f3529.png)

**Comment by leoscimino** [comment]
O problema foi corrigido
